### ISSUE TITLE
Facing issue while importing database in simpledb via sdbport

### ISSUE THREAD

**Issue by dinshawraje** [intuit/sdbport#13]
_I have installed the gem :_

```
gem install sdbport -v 0.2.0
```

_and run the following command :_

```
sdbport import -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -r us-west-1 -n data -i /tmp/test-domain-dump
```

then its giving following error :

```
/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/lib/sdbport/domain/import.rb:24:in `gets': Is a directory @ io_fillbuf - fd:7 /home/projects/smb/attsp-script/domain-dump (Errno::EISDIR)
    from /home/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/lib/sdbport/domain/import.rb:24:in `import'
    from /home/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/lib/sdbport/domain.rb:14:in `import'
    from /home/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/lib/sdbport/cli/import.rb:21:in `import'
    from /home/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/lib/sdbport/cli.rb:26:in `start'
    from /home/.rvm/gems/ruby-2.1.5/gems/sdbport-0.2.1/bin/sdbport:6:in `<top (required)>'
    from /home/.rvm/gems/ruby-2.1.5/bin/sdbport:23:in `load'
    from /home/.rvm/gems/ruby-2.1.5/bin/sdbport:23:in `<main>'
    from /home/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /home/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Please help me out in solving this. Thank's in advance !!**

**Comment by bw-intuit** [comment]
@dinshawraje it looks like  /tmp/test-domain-dump is a directory.  Is there a file within the directory you are trying to load?  Also, you may want to use the latest version 0.4.1

**Comment by dinshawraje** [comment]
I am facing this issue while using latest version 0.4.1 and yes in this directory there is abcd.json file present

**Comment by bw-intuit** [comment]
@dinshawraje sorry, to clarify, you need to pass it the name of the file:

```
sdbport import -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -r us-west-1 -n data -i /tmp/test-domain-dump/abcd.json
```

Let me know if that works.
